#!/bin/bash

export ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )" # change to actual architecture location


function execute {
  case "$1" in
    "--install"|"-i")
      install
      return
    ;;
  esac
  case "$1" in
    "--run"|"-r")
      run
      return
    ;;
  esac

  help
}

function install {
   docker build --tag molecule_image .

}

function run {
   declare TTY="-ti"
   declare FORCE_BUILD=0
   declare IMAGE_NAME="molecule_image"

  docker run ${TTY} \
    --rm \
    --volume "/var/run/docker.sock:/var/run/docker.sock" \
    --volume ${ROOT}/base:/root/molecule/base \
    ${IMAGE_NAME} \
    bash -c "$*"
}

function help {
  say "
@b[[Carmelo infame per te sole le lame]]

@yellow[[Usage:]]
@green[[  -i,\t--install]]\t\tBuild Dday image
@green[[  -r,\t--run]]\t\t\tLaunch Command
@green[[  -h,\t--help]]\t\t\tShow this help
"

}

function say {
    echo -e "$@" | sed \
		-e "s/\(\(@\(red\|green\|yellow\|blue\|magenta\|cyan\|white\|reset\|b\|u\)\)\+\)[[]\{2\}\(.*\)[]]\{2\}/\1\4@reset/g" \
		-e "s/@red/$(tput setaf 1)/g"     \
		-e "s/@✘/$(tput setaf 1)/g"     \
		-e "s/@green/$(tput setaf 2)/g"   \
		-e "s/@✔/$(tput setaf 2)/g"   \
		-e "s/@yellow/$(tput setaf 3)/g"  \
		-e "s/@blue/$(tput setaf 4)/g"    \
		-e "s/@magenta/$(tput setaf 5)/g" \
		-e "s/@cyan/$(tput setaf 6)/g"    \
		-e "s/@white/$(tput setaf 7)/g"   \
		-e "s/@reset/$(tput sgr0)/g"      \
		-e "s/@b/$(tput bold)/g"          \
		-e "s/@u/$(tput sgr 0 1)/g"
}


if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        help
		exit
fi


if [ "$1" = "--install" ] || [ "$1" = "-i" ]; then
        install
		exit
fi

if [ "$1" = "--run" ] || [ "$1" = "-r" ]; then
        shift
        run $@
		exit
fi

help
